### ISSUE TITLE
SlipLib Version 0.1.0 Not In PyPi

### ISSUE THREAD

**Issue by kb1lqc** [rhjdjong/SlipLib#3]
The [latest SlipLib PyPi](https://pypi.python.org/pypi/sliplib/0.0.1) package is V 0.0.1 which does not match the current GitHub master of 0.1.0. This leaves out functionality that is currently documented on master and therefore makes the use of SlipLib harder.

I'd like to see the latest code be released on PyPi for V0.1.0 if possible. Thanks! Currently using it for @FaradayRF projects.

**Comment by rhjdjong** [comment]
Hello,
Thanks for your interest in SlipLib. This project is still very much in alpha-state. I have been working on and off (mostly off :-)) on this, trying to get a workable package that would also support async IO operations. I was actually planning to do some substantial work on this package in the upcoming Christmas break.
If you could give me an indication of what you are using / need from the current PyPI version, I can see if I can keep that functionality in. No guarantees though.

**Comment by kb1lqc** [comment]
Hey @rhjdjong thanks for the quick response! I am actually doing very similar work. I've been trying to get sliplib and pyserial to work with asyncio as well over on https://github.com/FaradayRF/faradayio/issues/3.

The project I am working on is Faraday, our radio communicates via USB serial and the new software I am writing is `faradayio`. This is documented in https://github.com/FaradayRF/faradayio/issues/4 and the following high-level block diagram:

![image](https://user-images.githubusercontent.com/331540/34052659-2305bbce-e178-11e7-9451-900f75dc1d95.png)

You can see even more of what we're doing and our hardware here: https://faradayrf.com/

Thanks for SlipLib!

**Comment by rhjdjong** [comment]
Hello @kb1lqc. As you may have noticed, I updated the SlipLib package over the last few days. I hope you find the updated version useful. If not, please let me know. And if you would like to contribute the PySerial wrapper you are developing to this project, that would be very welcome -- I don't have that much experiecne with PySerial that I am comfortable doing that myself.
Since the subject of this issue (the inconsistency between PyPI and GitHub versions) is now solved, I will now close this issue. Thanks for using SlipLib, even in this stage of development.

**Comment by kb1lqc** [comment]
@rhjdjong thanks! It appears to be working! https://travis-ci.org/kb1lqc/faradayio/builds/323692650
